steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'
      - '${_SUBDIR}'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'studymatch-runtime@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'EUREKA_ENABLED=false,SPRING_PROFILES_ACTIVE=prod'
      - '--set-env-vars'
      - '^##^USER_SERVICE_URL=${_USER_SERVICE_URL}##PROFILE_SERVICE_URL=${_PROFILE_SERVICE_URL}##GROUP_SERVICE_URL=${_GROUP_SERVICE_URL}##AI_SERVICE_URL=${_AI_SERVICE_URL}##CHAT_SERVICE_URL=${_CHAT_SERVICE_URL}##SOCIAL_SERVICE_URL=${_SOCIAL_SERVICE_URL}##CORS_ALLOWED_ORIGINS=${_CORS_ALLOWED_ORIGINS}'
      - '--set-secrets'
      - 'JWT_SECRET_KEY=studymatch-jwt-secret:latest'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--allow-unauthenticated'
      - '--quiet'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'

substitutions:
  _REGION: asia-southeast1
  _REPOSITORY: studymatch-images
  _SERVICE: api-gateway
  _SUBDIR: ./api-gateway
  _TAG: latest
  _USER_SERVICE_URL: https://user-service-36417266010.asia-southeast1.run.app
  _PROFILE_SERVICE_URL: https://profile-service-36417266010.asia-southeast1.run.app
  _GROUP_SERVICE_URL: https://group-service-36417266010.asia-southeast1.run.app
  _AI_SERVICE_URL: https://ai-service-36417266010.asia-southeast1.run.app
  _CHAT_SERVICE_URL: https://chat-service-36417266010.asia-southeast1.run.app
  _SOCIAL_SERVICE_URL: https://social-service-36417266010.asia-southeast1.run.app
  _CORS_ALLOWED_ORIGINS: 'http://localhost:3000,https://studymatch-frontend-36417266010.asia-southeast1.run.app,https://studymatch.nlu.id.vn'

options:
  logging: CLOUD_LOGGING_ONLY
