server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  security:
    jwt:
      secret-key: nlu_echo_by_phuc_lam_2004_this_is_be_for_applicati
