spring.application.name=api-gateway
server.port=${PORT:8080}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=5
app.security.jwt.secret-key=${JWT_SECRET_KEY:nlu_echo_by_phuc_lam_2004_this_is_be_for_applicati}

# CORS origins
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# Gateway routes
spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.routes[0].id=user-service-route
spring.cloud.gateway.routes[0].uri=${USER_SERVICE_URL:lb://USER-SERVICE}
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**,/api/users/**,/api/auth/**,/api/verify-email/**,/api/admin/users/**,/api/reports/**,/api/admin/reports/**,/api/admin/overview/**,/api/super-admin/**,/api/public/admin-invitations/**,/api/admin/profile,/api/admin/change-password

spring.cloud.gateway.routes[1].id=profile-service-route
spring.cloud.gateway.routes[1].uri=${PROFILE_SERVICE_URL:lb://PROFILE-SERVICE}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/onboarding/**,/api/cohorts/**,/api/subjects/**,/api/academic-terms/**,/api/profile/**,/api/admin/subjects/**,/api/admin/cohorts/**,/api/admin/academic-terms/**,/api/admin/curriculums/**,/api/admin/profiles/**

spring.cloud.gateway.routes[2].id=group-service-route
spring.cloud.gateway.routes[2].uri=${GROUP_SERVICE_URL:lb://GROUP-SERVICE}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/groups/**,/api/study-sessions/**,/api/admin/sessions/**,/api/admin/groups/**

spring.cloud.gateway.routes[3].id=ai-service-route
spring.cloud.gateway.routes[3].uri=${AI_SERVICE_URL:lb://AI-SERVICE}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/matching-items/**,/api/study-feedbacks/**,/api/admin/matching/**,/api/recommend-users/**

spring.cloud.gateway.routes[4].id=chat-service-route
spring.cloud.gateway.routes[4].uri=${CHAT_SERVICE_URL:lb://CHAT-SERVICE}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/admin/chat/**,/messages/**,/video-calls/**,/api/chat/**,/conversation/**,/ws/**,/ws

spring.cloud.gateway.routes[5].id=social-service-route
spring.cloud.gateway.routes[5].uri=${SOCIAL_SERVICE_URL:lb://SOCIAL-SERVICE}
spring.cloud.gateway.routes[5].predicates[0]=Path=/social/**,/api/documents/**,/api/admin/documents/**

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG