spring.application.name=api-gateway
server.port=8080


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=5
# Gateway routes
spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.gateway.routes[0].id=user-service-route
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**



spring.cloud.gateway.routes[1].id=profile-service-route
spring.cloud.gateway.routes[1].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/onboarding/**,/api/cohorts/**,/api/subjects/**,/api/academic-terms/**

spring.cloud.gateway.routes[2].id=group-service-route
spring.cloud.gateway.routes[2].uri=lb://GROUP-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/groups/**,/api/study-sessions/**,/api/admin/sessions/**



spring.cloud.gateway.routes[3].id=ai-service-route
spring.cloud.gateway.routes[3].uri=lb://AI-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/matching-items/**,/api/study-feedbacks/**,/api/admin/matching/**


spring.cloud.gateway.routes[4].id=social-service-route
spring.cloud.gateway.routes[4].uri=lb://SOCIAL-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/**


# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG