steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'
      - '${_SUBDIR}'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'studymatch-runtime@$PROJECT_ID.iam.gserviceaccount.com'
      - '--port'
      - '8080'
      - '--cpu'
      - '2'
      - '--memory'
      - '4Gi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--allow-unauthenticated'
      - '--quiet'
 
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'
 
substitutions:
  _REGION: asia-southeast1
  _REPOSITORY: studymatch-images
  _SERVICE: hate-speech-service
  _SUBDIR: ./hate_speech_service
  _TAG: latest

options:
  logging: CLOUD_LOGGING_ONLY
