package com.example.microservice.enums;

public enum StatusCode {
    INVALID_TOKEN ,
    INVALID_REFRESH_TOKEN,
    USER_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED,
    ACCESS_DENIED,
    EMAIL_ALREADY_IN_USE, INVALID_FILE, PASSWORD_INCORRECT, TOKEN_USED, TOKEN_EXPIRED, SUCCESS,
    REPORT_NOT_FOUND, DUPLICATE_REPORT, SELF_REPORT_NOT_ALLOWED, TARGET_NOT_FOUND, USER_LOCKED,
    EMAIL_ALREADY_USED_BY_STUDENT, INVITATION_NOT_FOUND, INVITATION_EXPIRED, INVITATION_ALREADY_USED
}


