steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'
      - '${_SUBDIR}'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'studymatch-runtime@$PROJECT_ID.iam.gserviceaccount.com'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:${_REGION}:studymatch-mysql'
      - '--set-env-vars'
      - 'DB_USER=studymatch_app,DB_NAME=db_profile_service,DB_HOST=/cloudsql/$PROJECT_ID:${_REGION}:studymatch-mysql,DB_PORT=3306,API_GATEWAY_URL=${_API_GATEWAY_URL}'
      - '--set-secrets'
      - 'DB_PASSWORD=studymatch-db-password:latest'
      - '--port'
      - '8080'
      - '--cpu'
      - '1'
      - '--memory'
      - '2Gi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '1'
      - '--allow-unauthenticated'
      - '--quiet'
 
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}'
 
substitutions:
  _REGION: asia-southeast1
  _REPOSITORY: studymatch-images
  _SERVICE: recommender-service
  _SUBDIR: ./recommender-service
  _TAG: latest
  _API_GATEWAY_URL: https://api-gateway-36417266010.asia-southeast1.run.app

options:
  logging: CLOUD_LOGGING_ONLY
