server:
  port: ${PORT:8086}

spring:
  application:
    name: GROUP-SERVICE

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: ${DB_URL:jdbc:mysql://35.198.241.223:3306/db_group_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=%2B07:00}
    username: ${DB_USERNAME:studymatch-mysql}
    password: ${DB_PASSWORD:Tai@83soctrang}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:5}
      minimum-idle: ${DB_MIN_IDLE:0}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      PROFILE-SERVICE:
        url: ${PROFILE_SERVICE_URL:}
      USER-SERVICE:
        url: ${USER_SERVICE_URL:}
      CHAT-SERVICE:
        url: ${CHAT_SERVICE_URL:}


app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:nlu_echo_by_phuc_lam_2004_this_is_be_for_applicati}

  zego:
    app-id: ${ZEGO_APP_ID:338381907}
    server-secret: ${ZEGO_SERVER_SECRET:85bbbac318483ddc14c7b8e2aad83fbb}
    token-ttl-seconds: 7200

google:
  client-id: ${GOOGLE_CLIENT_ID:714586252342-f47e1oar4i153si4gp61i15v7lg625ft.apps.googleusercontent.com}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dx2prhbqh}
  api-key: ${CLOUDINARY_API_KEY:174824789952654}
  api-secret: ${CLOUDINARY_API_SECRET:sQ-ju5OkJXRzniGUoVCa-68ao8o}

