package com.example.microservice.config;

public enum EnumEvent {
    NEW_MESSAGE ,
    MESSAGE_UPDATED,
    MESSAGE_ACK,
    MESSAGE_SENT,
    FORWARD_MESSAGE,
    MESSAGE_DELIVERED,
    MESSAGE_SEEN,

    NEW_REPLY,
    READ_RECEIPT,
    MESSAGE_RECALL,
    MESSAGE_MODERATED,
    MESSAGE_PIN,
    MESSAGE_UNPIN,
    REACTION_ADD,
    REACTION_ACK,
    SEND_REPLY_MESSAGE,
    VIDEO_CALL_INVITE,
    VIDEO_CALL_ACCEPTED,
    VIDEO_CALL_REJECTED,
    VIDEO_CALL_ENDED,
    USER_PRESENCE,
    CLIENT_READY,
    STUDY_SESSION_REMINDER,
    STUDY_SESSION_CREATED,
    GROUP_INVITATION_RECEIVE,
    GROUP_INVITATION_REJECTED,
    GROUP_MEMBER_KICKED
}
